function net  = initializeMitochondria()
f=1/100 ;
net.layers = {} ;
net.classes = {1,2};
net.layers{end+1} = struct('type', 'conv', ...
    'filters', f*randn(13,13,1,10, 'single'), ...
    'biases', zeros(1, 10, 'single'), ...
    'filtersLearningRate', 1, ...
     'biasesLearningRate', 2, ...
    'stride', 5, ...
    'pad', 0) ;
net.layers{end+1} = struct('type', 'pool', ...
    'method', 'avg', ...
    'pool', [2 2], ...
    'stride', 2 , ...
    'pad', [0 1 0 1]) ; % Emulate caffe
% 3 relu1
net.layers{end+1} = struct('type', 'relu') ;


net.layers{end+1} = struct('type', 'conv', ...
    'filters', f*randn(5,5,10,20, 'single'),...
    'biases', zeros(1,20,'single'), ...
    'filtersLearningRate', 1, ...
     'biasesLearningRate', 2, ...
    'stride', 2 , ...
    'pad', 0) ;
net.layers{end+1} = struct('type', 'pool', ...
    'method', 'max', ...
    'pool', [2 2], ...
    'stride', 2, ...
    'pad', [0 1 0 1]) ; % Emulate caffe
% 3 relu1
%net.layers{end+1} = struct('type', 'relu') ;

net.layers{end+1} = struct('type', 'conv', ...
    'filters', f*randn(5,5,20,50, 'single'),...
    'biases', zeros(1,50,'single'), ...
    'filtersLearningRate', 1, ...
     'biasesLearningRate', 2, ...
    'stride', 1 , ...
    'pad', 0) ;
% net.layers{end+1} = struct('type', 'pool', ...
%     'method', 'max', ...
%     'pool', [2 2], ...
%     'stride', 2, ...
%     'pad', [0 1 0 1]) ; % Emulate caffe

net.layers{end+1} = struct('type', 'dropout', ...
                           'rate', 0.5) ;
                       

                       
net.layers{end+1} = struct('type', 'conv', ...
    'filters', f*randn (1,1,50,200, 'single'),...
    'biases', zeros(1,200,'single'), ...
    'filtersLearningRate', 1, ...
    'biasesLearningRate', 2, ...
    'stride', 1, ...
    'pad', 0) ;

%net.layers{end+1} = struct('type', 'relu') ;

net.layers{end+1} = struct('type', 'conv', ...
    'filters', f*randn(1,1,200,2, 'single'),...
    'biases', zeros(1,2,'single'), ...
    'filtersLearningRate', 1, ...
    'biasesLearningRate', 2, ...
    'stride', 1, ...
    'pad', 0) ;

net.layers{end+1} = struct('type', 'softmaxloss') ;
end